name: SandCastle
favicon: null
layout_spectrum: 0.1964
typography_spectrum: 0.39029
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5625
  lightness: 0.6938826888799667
  saturation: 0.4007130484096706
  rhythmicContrast: 0.3866688183043152
purpose: []
